apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: minikube-sqlserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: minikube-sqlserver
    spec:
      containers:
      - name: minikube-sqlserver
        image: mcr.microsoft.com/mssql/server:2019-RC1-ubuntu
        ports:
        - containerPort: 1433
        env:
        - name: SA_PASSWORD
          value: "Testing1122"
        - name: ACCEPT_EULA
          value: "Y"
---
apiVersion: v1
kind: Service
metadata:
  name: minikube-sqlserver-service
spec:
  ports:
  - name: minikube-sqlserver
    port: 1433
    targetPort: 1433
  selector:
    name: minikube-sqlserver
  type: ClusterIP