FROM microsoft/mssql-server-linux:2017-GA

# Create sql script directory
RUN mkdir -p /usr/src/sqlscript
WORKDIR /usr/src/sqlscript

# Bundle script source
COPY ./shell /usr/src/sqlscript

# Grant permissions for the import-data script to be executable
RUN chmod +x /usr/src/sqlscript/restoredbs.sh
# RUN chmod 755 /usr/src/sqlscript

CMD /bin/bash ./entrypoint.sh