apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-aks-mssql-systemdbs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: sc-aks-demo
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-aks-mssql-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: sc-aks-demo
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-aks-mssql-logs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: sc-aks-demo
  resources:
    requests:
      storage: 5Gi