apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-aks-demo
provisioner: kubernetes.io/azure-disk
parameters:
  storageaccounttype: Standard_LRS
  kind: Managed

# https://kubernetes.io/docs/concepts/storage/storage-classes/#azure-disk
#apiVersion: storage.k8s.io/v1
#kind: StorageClass
#metadata:
#  name: sc-aks-demo
#provisioner: kubernetes.io/azure-file
#parameters:
#  skuName: Standard_LRS
#  location: uksouth
#  storageAccount: azure_storage_account_name